root - INFO - Бот запускается
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468A83898>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468A83FD0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468AA1048>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468AA1400>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=1 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468AA1390>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468AA1940>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468AA1A58>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468AA1C18>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=2 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468AA1630>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468ACE1D0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468AA1EF0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468AA1978>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=3 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468AA1E48>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468AA1828>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468AA1550>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468AA13C8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=4 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468AA1C50>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468ACE438>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468ACE550>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot629476291:AAHapHDKGqjtE9Y4UbzHNDGFQo-X6dXD1KI/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F468ACE710>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=5 max_retries=-1
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
